### ISSUE TITLE
scroll 트랜지션에서 duration 주입할 수 있는 인터페이스는 있는데, 값을 쓰지 않습니다.

### ISSUE THREAD

**Issue by SINHOLEE** [meursyphus/ssgoi#1]
[해당 코드](https://github.com/meursyphus/ssgoi/blob/20b686868c5bc558d6e3b19dbc02c61df34b1406/src/lib/transitions/scroll.ts#L7-L23)를 보면, duration을 인자로 받을 수 있지만 인자로 받은 값을 사용하지 않아 버그인걸로 착각했어요.

```typescript
	in(node, { reverse = false ,duration}: { duration?: number; reverse?: boolean }) {
		const height = window.innerHeight - node.clientTop;
		const _duration = duration ?? (height / VELOCITY);

		return {
			duration:_duration,
			css(_, u) {
				return `transform: translateY(${(reverse ? 1 : -1) * u * height}px)`;
			}
		};
	},

```

이렇게 하는건 어떨지 제안합니다.

**Comment by Moon-DaeSeung** [comment]
I did change duration into velocity for consistent develop experience. check this
