### ISSUE TITLE
npm error Could not resolve dependency: npm error peer svelte@"^4.0.0" from ssgoi@1.0.1

### ISSUE THREAD

**Issue by 7999999166** [meursyphus/ssgoi#12]
can We Use it With  --force or --legacy-peer-deps ?? 
currently i am using svelte5.0.0-next.243

**Comment by Moon-DaeSeung** [comment]
I think you can use it with --force or --legacy-peer-deps.
If svelte 5 is stable, I will support svelte4 and 5

**Comment by Moon-DaeSeung** [comment]
@7999999166 hello, now it is migrated into svelte5
