### ISSUE TITLE
[docs] Docs site Key Features section font color is light gray, not black

### ISSUE THREAD

**Issue by injae-kim** [meursyphus/ssgoi#4]
![image](https://github.com/user-attachments/assets/c86a6244-6ff1-44d2-b98a-8fda4012a194)

I found that [docs](https://ssgoi.pages.dev/) Key Feature's font color is **light gray, not black** when I open docs **first time**.
can we fix font color to black?

FYI, I found ssgoi by [linkedin](https://www.linkedin.com/posts/%EB%AC%B8%EB%8C%80%EC%8A%B9_webdevelopment-ssgoi-crossbrowsercompatibility-activity-7225545242005946368-6z2d?utm_source=share&utm_medium=member_desktop) post 😃

**Comment by Moon-DaeSeung** [comment]
thank you for reporting
